# Base URL for development environment
[development]
baseURL = "http://localhost:1313/"

# Base URL for production environment
[production]
baseURL = "https://billraymond.github.io/bill-talks-ai-website/"

# Additional settings
languageCode = 'en-us'
title = 'Bill Talks AI'
theme = 'bill-talks-ai'


