name: Build Bill Talks AI website

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # you can trigger the workflow manually

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true # this workflow stops other concurrent workflows from running

jobs:
  build-and-copy-site-to-prod:
    runs-on: ubuntu-latest
    env:
      WORKSPACE_PATH: /workspaces/
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true # Fetch Git submodules that Hugo might use

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: my-custom-image:latest

    - name: Run Docker container, build with Hugo, and list public contents
      run: |
        docker run --name temp-container -v ${{ github.workspace }}:${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }} my-custom-image:latest /bin/bash -c "\
          cd ${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }} && 
          set -x; \
          echo 'Here is a list of the files in ${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }}' && \
          ls -la && \
          echo 'Install Bootstrap just in case files are missing' && \
          npm install bootstrap && \
          echo 'Use package.json file to copy bootstrap files to the static folder' && \
          npm run copy-bootstrap && \
          echo 'Atttempting to build hugo with hugo -s . -d public' && \
          hugo -s . -d public --gc --cleanDestinationDir --minify --logLevel debug"
