name: Build Bill Talks AI website

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # you can trigger the workflow manually

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true # this workflow stops other concurrent workflows from running

jobs:
  build-bill-talks-ai-website:
    runs-on: ubuntu-latest
    env:
      WORKSPACE_PATH: /workspaces/ # when the action opens the dockerfile, use this as the top-level folder
      REPO_NAME: ${{ github.event.repository.name }} # when the action opens the dockerfile, use this as the top-level sub-folder
      BILL_TALKS_AI_PAT: ${{ secrets.BILL_TALKS_AI_PAT }} # Secret code created from developer settings

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true # Fetch Git submodules that Hugo might use

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5 # In this case, used for building the Dockerfile, not for pushing
      with:
        context: .
        file: ./Dockerfile # Open the dockerfile in this GitHub repo
        load: true
        tags: my-custom-image:latest # temporary image name and tag

    - name: Run Docker container, build with Hugo, and list public contents
      run: |
        docker run --name temp-container -v ${{ github.workspace }}:${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }} my-custom-image:latest /bin/bash -c "\
          cd ${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }} && 
          set -x; \
          echo 'Here is a list of the files in ${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }}' && \
          ls -la && \
          echo 'Install Bootstrap just in case files are missing' && \
          npm install bootstrap && \
          echo 'Use package.json file to copy bootstrap files to the static folder' && \
          npm run copy-bootstrap && \
          echo 'Build the Hugo site' && \
          hugo -s . -d public --gc --cleanDestinationDir --minify --logLevel debug"

    - name: Checkout target repository in a separate directory
      uses: actions/checkout@v4
      with:
        repository: 'BillRaymond/bill-talks-ai-website'
        token: ${{ secrets.BILL_TALKS_AI_PAT }}
        path: 'target_repo'
        ref: main

    - name: Sync site content to target repository
      run: |
        echo 'rsync'
        rsync -av --delete public/ target_repo/

    - name: Push changes to target repository
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.BILL_TALKS_AI_PAT }}
        directory: target_repo
        branch: main
