name: Deploy Hugo Site

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight GMT
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          repository: 'BillRaymond/bill-talks-ai-website-repo'
          path: 'source'

      - name: Build Hugo Site using Docker
        uses: docker://billraymond/billtalksaiimage:latest
        with:
          args: hugo -s source/ -d public

      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: 'BillRaymond/bill-talks-ai-website'
          token: ${{ secrets.BILL_TALKS_AI_PAT }}
          path: 'target'

      - name: Clear previous site content
        run: |
          rm -rf target/*
          
      - name: Copy new site to target repo
        run: |
          cp -r source/public/* target/
          
      - name: Commit and Force Push to Target Repo
        run: |
          cd target
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Deploy Hugo site" || echo "No changes to commit."
          git push --force

