name: Dockerfile Dev Environment List

on: [push, pull_request]

jobs:
  build-and-list-contents:
    runs-on: ubuntu-latest
    env:
      WORKSPACE_PATH: /workspaces/
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: my-custom-image:latest

    - name: Run Docker container, build with Hugo, and list public contents
      run: |
        docker run --name temp-container -v ${{ github.workspace }}:${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }} my-custom-image:latest /bin/bash -c "\
          cd ${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }} && 
          echo 'Here is a list of the files in ${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }}' \
          ls -la"
