name: Dockerfile Dev Environment List

on: [push, pull_request]

jobs:
  build-and-list-contents:
    runs-on: ubuntu-latest
    # Define environment variables for use in this job
    env:
      WORKSPACE_PATH: /workspaces/
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: my-custom-image:latest

    - name: Run Docker container and list workspace contents
      run: |
        docker run --name temp-container -v ${{ github.workspace }}:${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }} my-custom-image:latest ls -la ${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }}
