name: Build and Deploy Jekyll Site

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 12 midnight GMT every night
  push:
    branches:
      - main

# Using concurrency to ensure only the latest run is executed for a given branch
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
        with:
          repository: 'BillRaymond/bill-talks-ai-website-repo'
          path: website

      - name: Build the Docker image
        run: docker build . -t jekyll-builder

      - name: Prepare and Build Jekyll Site
        run: |
          docker run --name jekyll-site jekyll-builder sh -c "bundle install && bundle update && bundle exec jekyll build"
          docker cp jekyll-site:/workspaces/bill-talks-ai-website-repo/website/_site ./_site

      - name: Check out GitHub Pages repository
        uses: actions/checkout@v2
        with:
          repository: 'BillRaymond/bill-talks-ai-website'
          token: ${{ secrets.BILL_TALKS_AI_PAT }}

      - name: Copy site output to GitHub Pages repository
        run: |
          cp -r ./_site/* ./
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy Jekyll site" -a || echo "No changes to commit"
          git push
