name: Publish Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2
      with:
        path: 'source-repo'

    - name: Setup Git for Deployment
      run: |
        git config --global "user.name" "Bill Raymond"
        git config --global user.email "bill.raymond@cambermast.com"

    - name: Checkout Destination Repository
      uses: actions/checkout@v2
      with:
        repository: 'BillRaymond/bill-talks-ai-website'
        token: ${{ secrets.JEKYLLNEW_PAT }}
        path: 'destination-repo'

    - name: Copy Site Files
      run: |
        rsync -av --progress source-repo/website/_site/ destination-repo/ --exclude .git

    - name: Commit and Push to Destination Repository
      run: |
        cd destination-repo
        git add .
        git commit -m "Update Jekyll site"
        git push
